title: Page

options:
  preview: true
  status: true
  template: true
  url: true
  delete: true

icon: file-code-o

pages: false
files: true

fields:
  title:
    label: Titre
    type:  text

  text:
    label: Texte
    extends: markdown
