title: Produit
icon: book

options:
  preview: true
  status: true
  template: true
  url: true
  delete: true

pages: false
files:
  fields:
    caption:
      label: Légende
      type: markdown
      tools:
        - link
fields:
  previewfiles:
    type: previewfiles

  title:
    label: Titre
    type:  text

  cover:
    label: Photo de profil
    type: image
    required: true

  metas: metas

  text: markdown
