title: Projet
icon: book

options:
  preview: true
  status: true
  template: true
  url: true
  delete: true

pages:
  build:
    - title: Résumé
      uid: resume
      template: article
      num: 1
    - title: Détails
      uid: details
      template: article
      num: 2

files:
  fields:
    caption:
      label: Légende
      type: markdown
      tools:
        - link
fields:
  previewfiles:
    type: previewfiles

  title:
    label: Titre
    type:  text

  cover:
    label: Photo de couverture
    type: image
    required: true

  metas: metas

  description:
    label: Description
    extends: markdown
